//! Animated GIF, written here, for the same reason the PNG codec is written
//! here: a translation of cbirds `gif.c` (commit
//! cc446fc3cb80733371c62676533adcac2fc10002).
//!
//! The point of --record is that the demo in the README can be regenerated by
//! anyone who clones the repository, with one command and no tools they have
//! to install first. That rules out shelling out to anything, so: a global
//! colour table built from the frames themselves, and LZW.
//!
//! The C's stdio calls map onto [`std::fs::File`] behind a [`BufWriter`]:
//! `fopen(path, "wb")` is [`File::create`], `fputc`/`fwrite` are buffered
//! writes, `ftell`/`fseek` are [`Seek`] calls (which flush first, as `fseek`
//! does), and `fclose` is the final flush. Two consequences of the buffering
//! differ in detail from stdio's and are not part of the compared behavior:
//! after a write error the byte count reflects what this buffer had accepted,
//! and an error reported only by close(2) after a successful flush cannot be
//! observed through `std` (dropping a [`File`] discards it).

#![forbid(unsafe_code)]

use std::fmt;
use std::fs::File;
use std::io::{BufWriter, Seek, SeekFrom, Write};
use std::path::Path;

use super::Image;

/// `gif_status_t` without `GIF_OK`, which is `Ok(..)`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum GifError {
    Argument,
    Memory,
    Io,
}

impl GifError {
    /// `gif_status_string` for this status.
    pub fn as_str(self) -> &'static str {
        match self {
            GifError::Argument => "invalid argument",
            GifError::Memory => "out of memory",
            GifError::Io => "write error",
        }
    }
}

impl fmt::Display for GifError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::error::Error for GifError {}

/// `gif_status_string` over a whole status, `GIF_OK` included.
pub fn gif_status_string(status: Result<(), GifError>) -> &'static str {
    match status {
        Ok(()) => "ok",
        Err(error) => error.as_str(),
    }
}

const GIF_COLOURS: usize = 256;
/// Eight bits, because the table is 256 long.
const GIF_MIN_CODE_SIZE: i32 = 8;
const GIF_CLEAR_CODE: i32 = 1 << GIF_MIN_CODE_SIZE;
const GIF_END_CODE: i32 = GIF_CLEAR_CODE + 1;
const GIF_FIRST_CODE: i32 = GIF_CLEAR_CODE + 2;
const GIF_MAX_CODE: i32 = 4095;
/// Colours are counted in five bits a channel: the difference between two
/// neighbouring buckets is below what anyone can see, and it turns the count
/// into one pass over a fixed table.
const QUANT_BITS: i32 = 5;
const QUANT_LEVELS: i32 = 1 << QUANT_BITS;
const QUANT_BUCKETS: usize = (QUANT_LEVELS * QUANT_LEVELS * QUANT_LEVELS) as usize;
/// `GIF_MAX_CODE + 1` by `GIF_COLOURS` entries.
const DICTIONARY_LENGTH: usize = (GIF_MAX_CODE as usize + 1) * GIF_COLOURS;

/// What [`GifWriter::close`] reports (`gif_close` and its out parameters).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct GifClosed {
    /// The first failure along the way, or of the close itself.
    pub status: Result<(), GifError>,
    /// Bytes written, the trailer included when it could be.
    pub bytes: usize,
    /// Frames written whole.
    pub frames: i32,
}

/// An animation being written (`gif_writer_t`).
pub struct GifWriter {
    file: BufWriter<File>,
    width: i32,
    height: i32,
    frames: i32,
    written: usize,
    status: Result<(), GifError>,
    have_palette: bool,
    palette: [[u8; 3]; GIF_COLOURS],
    /// Nearest palette entry, per bucket.
    bucket_to_index: Vec<u8>,
    /// One frame's worth.
    indices: Vec<u8>,
    // LZW state, kept here so a frame does not allocate.
    block: [u8; 255],
    block_length: usize,
    /// Hundredths of a second between frames.
    delay: i32,
    bits: u32,
    bit_count: i32,
    /// `GIF_MAX_CODE + 1` by `GIF_COLOURS`, -1 for empty.
    dictionary: Vec<i16>,
}

/// A buffer of `length` copies of `value`, `None` where `malloc` would have
/// returned NULL.
fn filled<T: Clone>(length: usize, value: T) -> Option<Vec<T>> {
    let mut buffer = Vec::new();
    buffer.try_reserve_exact(length).ok()?;
    buffer.resize(length, value);
    Some(buffer)
}

fn bucket_of(rgb: &[u8]) -> usize {
    let r = i32::from(rgb[0]) >> (8 - QUANT_BITS);
    let g = i32::from(rgb[1]) >> (8 - QUANT_BITS);
    let b = i32::from(rgb[2]) >> (8 - QUANT_BITS);
    ((r * QUANT_LEVELS + g) * QUANT_LEVELS + b) as usize
}

impl GifWriter {
    /// Creates the file and writes everything before the first frame
    /// (`gif_open`). `delay_hundredths` is what the viewer waits between
    /// frames; the palette is built from the first frame handed over, which
    /// for this program is representative: the background and the ramp are
    /// the whole image.
    ///
    /// The C's NULL `out` and `path` refusals cannot be expressed. Like the
    /// C, a file that cannot be created is [`GifError::Io`] even when memory
    /// also ran out, and an allocation failure after the file was created
    /// leaves it created and empty. Where the C would hand back a writer
    /// together with a failed status (a header write failing, which its
    /// buffer makes unreachable in practice), the writer is dropped here.
    pub fn open(
        path: &Path,
        width: i32,
        height: i32,
        delay_hundredths: i32,
    ) -> Result<GifWriter, GifError> {
        if width <= 0 || height <= 0 || width > 65535 || height > 65535 {
            return Err(GifError::Argument);
        }

        // calloc(1, sizeof(*w)): the bucket table is part of the C struct.
        let bucket_to_index = filled(QUANT_BUCKETS, 0u8).ok_or(GifError::Memory)?;
        let indices = filled(width as usize * height as usize, 0u8);
        let dictionary = filled(DICTIONARY_LENGTH, 0i16);
        let file = File::create(path);
        let (indices, dictionary, file) = match (indices, dictionary, file) {
            (Some(indices), Some(dictionary), Ok(file)) => (indices, dictionary, file),
            (_, _, Err(_)) => return Err(GifError::Io),
            // The file was created, and is closed as it is dropped.
            _ => return Err(GifError::Memory),
        };

        let mut w = GifWriter {
            file: BufWriter::new(file),
            width,
            height,
            frames: 0,
            written: 0,
            status: Ok(()),
            have_palette: false,
            palette: [[0; 3]; GIF_COLOURS],
            bucket_to_index,
            indices,
            block: [0; 255],
            block_length: 0,
            delay: 0,
            bits: 0,
            bit_count: 0,
            dictionary,
        };

        w.put_bytes(b"GIF89a");
        w.put_short(width);
        w.put_short(height);
        w.put_byte(0xf7); // Global table, 256 entries, 8 bits a colour.
        w.put_byte(0); // Background index.
        w.put_byte(0); // No aspect ratio.
        // The table itself is written by the first frame, once it is known,
        // so the header's remaining 768 bytes are reserved here and filled
        // then.
        for _ in 0..GIF_COLOURS * 3 {
            w.put_byte(0);
        }

        // Netscape's looping extension: the only way to say "forever".
        w.put_bytes(b"\x21\xff\x0bNETSCAPE2.0\x03\x01\x00\x00\x00");
        w.frames = 0;
        // The delay is per frame and goes in each graphic control block.
        w.delay = if delay_hundredths < 1 { 1 } else { delay_hundredths };
        w.status.map(|()| w)
    }

    fn put_byte(&mut self, byte: u8) {
        if self.status.is_err() {
            return;
        }
        if self.file.write_all(&[byte]).is_err() {
            self.status = Err(GifError::Io);
            return;
        }
        self.written += 1;
    }

    fn put_bytes(&mut self, data: &[u8]) {
        if self.status.is_err() {
            return;
        }
        if self.file.write_all(data).is_err() {
            self.status = Err(GifError::Io);
            return;
        }
        self.written += data.len();
    }

    fn put_short(&mut self, value: i32) {
        self.put_byte((value & 0xff) as u8);
        self.put_byte(((value >> 8) & 0xff) as u8);
    }

    /*========================== The colour table ===========================*/

    /// The most used buckets become the table, and every other bucket is
    /// pointed at whichever of them is nearest (`build_palette`). On this
    /// program's output the two hundred and fifty six most frequent colours
    /// cover better than 99.8% of the pixels, so the result is visually exact
    /// rather than merely close.
    fn build_palette(&mut self, frame: &Image) -> Result<(), GifError> {
        let (Some(mut counts), Some(mut sums)) =
            (filled(QUANT_BUCKETS, 0u32), filled(QUANT_BUCKETS * 3, 0u32))
        else {
            return Err(GifError::Memory);
        };

        let pixels = frame.width as usize * frame.height as usize;
        for rgb in frame.pixels.chunks_exact(4).take(pixels) {
            let bucket = bucket_of(rgb);
            counts[bucket] = counts[bucket].wrapping_add(1);
            for c in 0..3 {
                sums[bucket * 3 + c] = sums[bucket * 3 + c].wrapping_add(u32::from(rgb[c]));
            }
        }

        // The top entries by count, chosen by repeated selection: two hundred
        // and fifty six passes over the buckets is nothing next to the pixels.
        let mut used = 0usize;
        for _ in 0..GIF_COLOURS {
            let mut best: Option<usize> = None;
            let mut best_count = 0u32;
            for (bucket, &count) in counts.iter().enumerate() {
                if count > best_count {
                    best_count = count;
                    best = Some(bucket);
                }
            }
            let Some(best) = best else { break };
            for c in 0..3 {
                self.palette[used][c] = (sums[best * 3 + c] / counts[best]) as u8;
            }
            counts[best] = 0;
            used += 1;
        }
        if used == 0 {
            // A blank frame still needs one entry.
            self.palette[0] = [0; 3];
            used = 1;
        }
        for slot in used..GIF_COLOURS {
            self.palette[slot] = self.palette[0];
        }

        // Every bucket in the cube gets pointed at the nearest chosen colour,
        // once, so mapping a pixel afterwards is a single lookup.
        for bucket in 0..QUANT_BUCKETS {
            let level = bucket as i64;
            let levels = i64::from(QUANT_LEVELS);
            let r = (level / levels / levels) << (8 - QUANT_BITS);
            let g = ((level / levels) % levels) << (8 - QUANT_BITS);
            let b = (level % levels) << (8 - QUANT_BITS);
            let mut best_distance = -1i64;
            let mut best_slot = 0usize;
            for (slot, colour) in self.palette[..used].iter().enumerate() {
                let dr = r - i64::from(colour[0]);
                let dg = g - i64::from(colour[1]);
                let db = b - i64::from(colour[2]);
                let distance = dr * dr + dg * dg + db * db;
                if best_distance < 0 || distance < best_distance {
                    best_distance = distance;
                    best_slot = slot;
                }
            }
            self.bucket_to_index[bucket] = best_slot as u8;
        }
        self.have_palette = true;
        Ok(())
    }

    /*================================ LZW ==================================*/

    fn flush_block(&mut self) {
        if self.block_length == 0 {
            return;
        }
        self.put_byte(self.block_length as u8);
        let block = self.block;
        self.put_bytes(&block[..self.block_length]);
        self.block_length = 0;
    }

    fn put_code(&mut self, code: i32, width: i32) {
        self.bits |= (code as u32) << self.bit_count;
        self.bit_count += width;
        while self.bit_count >= 8 {
            self.block[self.block_length] = (self.bits & 0xff) as u8;
            self.block_length += 1;
            self.bits >>= 8;
            self.bit_count -= 8;
            if self.block_length == 255 {
                self.flush_block();
            }
        }
    }

    /// `encode_frame` over this frame's `indices`.
    fn encode_frame(&mut self) {
        let mut width = GIF_MIN_CODE_SIZE + 1;
        let mut next = GIF_FIRST_CODE;
        let count = self.indices.len();

        self.dictionary.fill(-1);
        self.block_length = 0;
        self.bits = 0;
        self.bit_count = 0;

        self.put_byte(GIF_MIN_CODE_SIZE as u8);
        self.put_code(GIF_CLEAR_CODE, width);
        if count == 0 {
            self.put_code(GIF_END_CODE, width);
            if self.bit_count > 0 {
                self.put_code(0, 8 - self.bit_count);
            }
            self.flush_block();
            self.put_byte(0);
            return;
        }

        let mut current = i32::from(self.indices[0]);
        for i in 1..count {
            let next_index = i32::from(self.indices[i]);
            let entry = current as usize * GIF_COLOURS + next_index as usize;
            let found = self.dictionary[entry];
            if found >= 0 {
                current = i32::from(found);
                continue;
            }
            self.put_code(current, width);
            if next <= GIF_MAX_CODE {
                self.dictionary[entry] = next as i16;
                // The width grows once the codes no longer fit, as the
                // decoder expects, and the table is cleared when it is full.
                if next == (1 << width) && width < 12 {
                    width += 1;
                }
                next += 1;
            } else {
                self.put_code(GIF_CLEAR_CODE, width);
                self.dictionary.fill(-1);
                next = GIF_FIRST_CODE;
                width = GIF_MIN_CODE_SIZE + 1;
            }
            current = next_index;
        }
        self.put_code(current, width);
        self.put_code(GIF_END_CODE, width);
        if self.bit_count > 0 {
            self.put_code(0, 8 - self.bit_count);
        }
        self.flush_block();
        self.put_byte(0); // End of the image's sub-blocks.
    }

    /*=============================== Writing ===============================*/

    /// Appends a frame (`gif_add_frame`): RGBA in, alpha ignored, a GIF frame
    /// is opaque. The first frame decides the palette.
    ///
    /// The C's NULL frame and NULL pixels are the empty [`Image`] here. A
    /// frame whose buffer does not hold `width * height * 4` bytes, which the
    /// C would read past, is refused as [`GifError::Argument`] too.
    pub fn add_frame(&mut self, frame: &Image) -> Result<(), GifError> {
        if frame.pixels.is_empty() {
            return Err(GifError::Argument);
        }
        self.status?;
        if frame.width != self.width || frame.height != self.height {
            return Err(GifError::Argument);
        }
        let pixels = self.width as usize * self.height as usize;
        if frame.pixels.len() != pixels * 4 {
            return Err(GifError::Argument);
        }

        if !self.have_palette {
            if let Err(status) = self.build_palette(frame) {
                self.status = Err(status);
                return self.status;
            }
            // Back to the reserved space and write the table we now know.
            if self.rewrite_palette().is_err() {
                self.status = Err(GifError::Io);
                return self.status;
            }
        }

        for (index, rgba) in self.indices.iter_mut().zip(frame.pixels.chunks_exact(4)) {
            *index = self.bucket_to_index[bucket_of(rgba)];
        }

        self.put_bytes(b"\x21\xf9\x04\x00"); // Graphic control, no disposal.
        self.put_short(self.delay);
        self.put_byte(0); // No transparent index.
        self.put_byte(0);

        self.put_byte(0x2c); // Image descriptor.
        self.put_short(0);
        self.put_short(0);
        self.put_short(self.width);
        self.put_short(self.height);
        self.put_byte(0); // No local table, not interlaced.

        self.encode_frame();
        if self.status.is_ok() {
            self.frames += 1;
        }
        self.status
    }

    /// `ftell`, `fseek(13)`, `fwrite` of the table, `fseek` back.
    fn rewrite_palette(&mut self) -> std::io::Result<()> {
        let here = self.file.stream_position()?;
        self.file.seek(SeekFrom::Start(13))?;
        self.file.write_all(self.palette.as_flattened())?;
        self.file.seek(SeekFrom::Start(here))?;
        Ok(())
    }

    /// Writes the trailer and closes (`gif_close`). Safe on a writer that
    /// failed along the way: the status is the first failure, and the counts
    /// are what was written before it.
    pub fn close(mut self) -> GifClosed {
        self.put_byte(0x3b); // Trailer.
        let mut status = self.status;
        let bytes = self.written;
        let frames = self.frames;
        // fclose: what is still buffered goes out, and the file is closed as
        // it is dropped.
        if self.file.flush().is_err() && status.is_ok() {
            status = Err(GifError::Io);
        }
        GifClosed { status, bytes, frames }
    }
}
